tasks: 
  - name: terraform
    before: |
      cd $PROJECT_ROOT
      source ./bin/install_terraform_CLI.sh
      source ./bin/generate_tfrc_credential.sh
      source ./bin/set_tf_alias.sh
      cp $PROJECT_ROOT/terraform.tfvars.example $PROJECT_ROOT/terraform.tfvars
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd $PROJECT_ROOT
      source ./bin/install_aws_cli.sh
      source ./bin/set_tf_alias.sh
  - name: http-server
    before: |
      cd $PROJECT_ROOT
      npm install --global http-server
    command:
      http-server
  - name: sinatra
    before: |
      cd $PROJECT_ROOT
      cd terratowns_mock_server/
      bundle install
      bundle exec ruby server.rb
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
    - phil294.git-log--graph
    - mhutchie.git-graph